### ISSUE TITLE
Multiple markers detection

### ISSUE THREAD

**Issue by dorkamotorka** [usrl-uofsc/stag_ros#4]
Is there any configuration file I could refer to, so that I will be able to detect multiple markers at the same time, that has different IDs?
I could replicate the single_config.cfg pattern, but I would assume that each marker has it's own corner matrix?

**Comment by tp4348** [comment]
I could replicate the single_config.cfg pattern, but I would assume that each marker has it's own corner matrix?

**Comment by tp4348** [comment]
I am thinking in terms of like generation 1000s of those markers but I think the largest HD library is something like 750

**Comment by MikeK4y** [comment]
If you want to detect multiple markers as a single bundle then you can refer to either the bundle_config_2.yaml or bundle_config_4.yaml. A bundle of markers is a set of markers that define a single object, so there is a single object origin and the corners of all the markers should refer to that origin.

If you want to detect multiple markers individually of each other then you can add more markers in the single_config.yaml in the tag group. For example, this config file will detect the two markers in the bundle_2.bag individually:

```yaml
tags:
  [
    {
      frame: "tag_27",
      id: 27,
      corners: [
        [-0.127,  0.059, 0.0],
        [-0.009,  0.059, 0.0],
        [-0.009, -0.059, 0.0]
      ]
    },
    {
      frame: "tag_63",
      id: 63,
      corners : [
        [-0.127,  0.059, 0.0],
        [-0.009,  0.059, 0.0],
        [-0.009, -0.059, 0.0]
      ]
    }
  ]
bundles:
  [
  ]

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
```
